import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/commonComponents/Header";
import { Toaster } from "react-hot-toast";
import Footer from "../components/commonComponents/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-gradient-to-br from-gray-900 via-zinc-800 to-gray-900`}
      >
        <Header />
        <Toaster />
        <div className="flex-grow pt-28 min-h-screen items-center">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
